# install-golang.yml
---
- name: Install golang
  hosts: localhost
  vars:
     - version: 1.21.6
  tasks:
    - name: Remove go from apt install
      apt:
        name:
        - golang
        - golang-doc
        - golang-go
        - golang-src
        state: absent
      become: true

    - name: Download go amd64 tar file
      get_url:
        url: https://go.dev/dl/go{{version}}.linux-amd64.tar.gz
        dest: /tmp/go-linux.tar.gz
        checksum: sha256:3f934f40ac360b9c01f616a9aa1796d227d8b0328bf64cb045c7b8c4ee9caea4
      when: ansible_architecture == "x86_64"
    
    - name: Download go arm64 tar file
      get_url:
        url: https://go.dev/dl/go{{version}}.linux-arm64.tar.gz
        dest: /tmp/go-linux.tar.gz
        checksum: sha256:e2e8aa88e1b5170a0d495d7d9c766af2b2b6c6925a8f8956d834ad6b4cacbd9a
      when: ansible_architecture == "arm64"

    - name: Delete previous installation
      file:
        path: /usr/local/go
        state: absent
      become: true

    - name: Extract and install go
      unarchive:
        src: /tmp/go-linux.tar.gz
        dest: /usr/local
      become: true

    - name: Delete downloaded tar file
      file:
        path: /tmp/go-linux.tar.gz
        state: absent

    - name: Add GOPATH env to .profile
      lineinfile:
        path: ~/.profile
        line: 'export GOPATH=$HOME/go'
        create: true
        state: present

    - name: Add go binary path to .profile
      lineinfile:
        path: ~/.profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

