# install-golang.yml
---
- name: Install golang
  hosts: localhost
  vars:
     - version: 1.23.0
  tasks:
    - name: Remove go from apt install
      apt:
        name:
        - golang
        - golang-doc
        - golang-go
        - golang-src
        state: absent
      become: true

    - name: Download go amd64 tar file
      get_url:
        url: https://go.dev/dl/go{{version}}.linux-amd64.tar.gz
        dest: /tmp/go-linux.tar.gz
        checksum: sha256:905a297f19ead44780548933e0ff1a1b86e8327bb459e92f9c0012569f76f5e3
      when: ansible_architecture == "x86_64"
    
    - name: Download go arm64 tar file
      get_url:
        url: https://go.dev/dl/go{{version}}.linux-arm64.tar.gz
        dest: /tmp/go-linux.tar.gz
        checksum: sha256:62788056693009bcf7020eedc778cdd1781941c6145eab7688bd087bce0f8659
      when: ansible_architecture == "arm64"

    - name: Delete previous installation
      file:
        path: /usr/local/go
        state: absent
      become: true

    - name: Extract and install go
      unarchive:
        src: /tmp/go-linux.tar.gz
        dest: /usr/local
      become: true

    - name: Delete downloaded tar file
      file:
        path: /tmp/go-linux.tar.gz
        state: absent

    - name: Add GOPATH env to .profile
      lineinfile:
        path: ~/.profile
        line: 'export GOPATH=$HOME/go'
        create: true
        state: present

    - name: Add go binary path to .profile
      lineinfile:
        path: ~/.profile
        line: 'export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin'
        create: true
        state: present

