# install-caddy.yml
---
- name: Install caddy webserver
  hosts: localhost
  tasks:
    - name: Install apt requirements
      apt:
        name:
        - debian-keyring
        - debian-archive-keyring
        - apt-transport-https
        - curl
        state: present
      become: true

    - name: Install Caddy signing key
      apt_key:
        url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
        state: present
      become: true  

    # https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt
    - name: Add caddy repository 1
      apt_repository:
        repo: "deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
        state: present

    - name: Update repositories cache and install caddy
      apt:
        name: caddy
        state: present
        update_cache: yes
      become: true
