# install-docker.yml
---
- name: Install docker
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Remove old versions
      apt:
        name:
        - docker.io
        - docker-doc
        - docker-compose
        - podman-docker
        - containerd
        - runc
        state: absent
      become: true

    - name: Install apt requirements
      apt:
        name:
        - ca-certificates 
        - curl
        - gnupg
        state: present
      become: true

    - name: Install Docker signing key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

      # https://docs.docker.com/engine/install/ubuntu/
    - name: Add Docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
      become: true

    - name: Update repositories cache and install docker
      apt:
        name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        state: present
        update_cache: yes
      become: true

    - name: Get current username
      shell: whoami
      register: current_user

    - name: Add current user to docker group
      user:
        name: "{{ current_user.stdout }}"
        groups: docker
        append: yes
      become: true
